spring:
  application:
    name: baro
  profiles:
    default: local
  ai:
    model:
      chat: ${SPRING_AI_MODEL_CHAT:none}
      embedding: ${SPRING_AI_MODEL_EMBEDDING:none}
      image: ${SPRING_AI_MODEL_IMAGE:none}
      audio:
        speech: ${SPRING_AI_MODEL_AUDIO_SPEECH:none}
        transcription: ${SPRING_AI_MODEL_AUDIO_TRANSCRIPTION:none}
      moderation: ${SPRING_AI_MODEL_MODERATION:none}
    openai:
      api-key: ${OPENAI_API_KEY:}

kakao:
  oauth:
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    client-id: ${KAKAO_REST_API_KEY:}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/v1/auth/kakao/callback}
