spring:
  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPENAI_API_KEY}

kakao:
  oauth:
    client-id: ${KAKAO_REST_API_KEY:dfaa961ef37590707b29fd637ef872bc}
    client-secret: ${KAKAO_CLIENT_SECRET:geyBPNYTcHLOL74mDiea9kTG139HkZgr}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/v1/auth/kakao/callback}
